sonar.projectKey=ahmed-nasir-mern-10pshine
sonar.projectName=Full Stack Notes Application
sonar.projectVersion=1.0

sonar.sources=frontend, backend
sonar.exclusions=**/node_modules/**,**/dist/**

sonar.language=js

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000